// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiMusicalLibrary.Data;

#nullable disable

namespace WebApiMusicalLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240507004618_SeCreanTablasPrincipales")]
    partial class SeCreanTablasPrincipales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiMusicalLibrary.Models.Albun", b =>
                {
                    b.Property<int>("IdAlbun")
                        .HasColumnType("int");

                    b.Property<int>("GenreIdGenre")
                        .HasColumnType("int");

                    b.Property<int>("IdBandSinger")
                        .HasColumnType("int");

                    b.Property<int>("IdGenre")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("IdAlbun");

                    b.HasIndex("GenreIdGenre");

                    b.HasIndex("IdBandSinger");

                    b.ToTable("Albun");
                });

            modelBuilder.Entity("WebApiMusicalLibrary.Models.BandSinger", b =>
                {
                    b.Property<int>("IdBandSinger")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Members")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StarDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdBandSinger");

                    b.HasIndex("IdCountry");

                    b.ToTable("BandSinger");
                });

            modelBuilder.Entity("WebApiMusicalLibrary.Models.Country", b =>
                {
                    b.Property<string>("IdCountry")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdCountry");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("WebApiMusicalLibrary.Models.Genre", b =>
                {
                    b.Property<int>("IdGenre")
                        .HasColumnType("int");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdGenre");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("WebApiMusicalLibrary.Models.Songs", b =>
                {
                    b.Property<int>("IdSong")
                        .HasColumnType("int");

                    b.Property<int>("IdAlbun")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Track")
                        .HasColumnType("int");

                    b.HasKey("IdSong");

                    b.HasIndex("IdAlbun");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("WebApiMusicalLibrary.Models.Albun", b =>
                {
                    b.HasOne("WebApiMusicalLibrary.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreIdGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiMusicalLibrary.Models.BandSinger", "BandSinger")
                        .WithMany()
                        .HasForeignKey("IdBandSinger")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BandSinger");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("WebApiMusicalLibrary.Models.BandSinger", b =>
                {
                    b.HasOne("WebApiMusicalLibrary.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WebApiMusicalLibrary.Models.Songs", b =>
                {
                    b.HasOne("WebApiMusicalLibrary.Models.Albun", "Albun")
                        .WithMany()
                        .HasForeignKey("IdAlbun")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Albun");
                });
#pragma warning restore 612, 618
        }
    }
}
